apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.requestprocessingservice.configmapname }}
data:
  appsettings.json: |-
    {
      "PolicyId": "00000000-0000-0000-0000-000000000000",
      "ContentManagementFlags": {
          "PdfContentManagement": {
          "Acroform": 1,
          "ActionsAll": 1,
          "EmbeddedFiles": 1,
          "EmbeddedImages": 1,
          "ExternalHyperlinks": 1,
          "InternalHyperlinks": 1,
          "Javascript": 1,
          "Metadata": 1,
          "Watermark": "Glasswall Processed"
          },
          "WordContentManagement": {
          "DynamicDataExchange": 1,
          "EmbeddedFiles": 1,
          "EmbeddedImages": 1,
          "ExternalHyperlinks": 1,
          "InternalHyperlinks": 1,
          "Macros": 1,
          "Metadata": 1,
          "ReviewComments": 1
          },
          "ExcelContentManagement": {
          "DynamicDataExchange": 1,
          "EmbeddedFiles": 1,
          "EmbeddedImages": 1,
          "ExternalHyperlinks": 1,
          "InternalHyperlinks": 1,
          "Macros": 1,
          "Metadata": 1,
          "ReviewComments": 1
          },
          "PowerPointContentManagement": {
          "EmbeddedFiles": 1,
          "EmbeddedImages": 1,
          "ExternalHyperlinks": 1,
          "InternalHyperlinks": 1,
          "Macros": 1,
          "Metadata": 1,
          "ReviewComments": 1
          }
      },
      "UnprocessableFileTypeAction": 2,
      "GlasswallBlockedFilesAction": 2,
      "NcfsRoutingUrl": "http://doesnt-exist.com/api",
      "ArchiveErrorReportMessage": "The archive contained files which do not comply with the current policy",
      "ArchivePasswordProtectedReportMessage": "The archive was password protected and unable to be analysed",
      "RebuildReportMessage": "The file does not comply with the current policy"
    } 