environment:
managementui:
  deployment:
    name: icap-management-ui
    port: 8080
  service:
    name: icap-management-ui-service
    port: 80
  config:
    transactionEventApiUrl: https://transaction-event-api/api/v1
    policyManagementApiUrl: https://policy-management-api/api/v1
policymanagementapi:
  fullnameOverride: policy-management-api
  replicaCount: 1
  imagePullSecrets: []
  # Optionally specify an array of imagePullSecrets.
  # Secrets must be manually created in the namespace.
  # ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
  #
  # This uses credentials from secret "myRegistryKeySecretName".
  # - name: myRegistryKeySecretName
  service:
    type: ClusterIP
    port: 443
  configuration:
    ShareName: transactions
    ASPNETCORE_URLS: "https://+:443"
  PolicyUpdateServiceEndpointCsv: https://policy-update-service.icap-adaptation.svc.cluster.local:10000/
  NcfsPolicyUpdateServiceEndpointCsv: https://ncfs-policy-update-service.icap-ncfs.svc.cluster.local:10001/
  deployment:
    containerPort: 443
  probes:
    enabled: false
  ingress:
    enabled: false
    annotations: {}
    # kubernetes.io/tls-acme: "true"
    path: /
    # hosts:
    #   - chart-example.local
    tls: []
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
  secrets: {}
  # Optionally specify a set of secret objects whose values
  # will be injected as environment variables by default.
  # You should add this section to a file like secrets.yaml
  # that is explicitly NOT committed to source code control
  # and then include it as part of your helm install step.
  # ref: https://kubernetes.io/docs/concepts/configuration/secret/
  #
  # This creates a secret "mysecret" and injects "mypassword"
  # as the environment variable mysecret_mypassword=password.
  # mysecret:
  #   mypassword: password
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
transactioneventapi:
  fullnameOverride: transaction-event-api
  replicaCount: 1
  imagePullSecrets: []
  # Optionally specify an array of imagePullSecrets.
  # Secrets must be manually created in the namespace.
  # ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
  #
  # This uses credentials from secret "myRegistryKeySecretName".
  # - name: myRegistryKeySecretName
  service:
    type: ClusterIP
    port: 443
  configuration:
    ShareName: transactions
  deployment:
    containerPort: 443
  probes:
    enabled: false
  ingress:
    enabled: false
    annotations: {}
    # kubernetes.io/tls-acme: "true"
    path: /
    # hosts:
    #   - chart-example.local
    tls: []
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
  secrets: {}
  # Optionally specify a set of secret objects whose values
  # will be injected as environment variables by default.
  # You should add this section to a file like secrets.yaml
  # that is explicitly NOT committed to source code control
  # and then include it as part of your helm install step.
  # ref: https://kubernetes.io/docs/concepts/configuration/secret/
  #
  # This creates a secret "mysecret" and injects "mypassword"
  # as the environment variable mysecret_mypassword=password.
  # mysecret:
  #   mypassword: password
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
imagestore:
  icapmanagementui:
    registry: ""
    repository: glasswallsolutions/icap-management-ui
    tag: develop-3b35ead
  policymanagementapi:
    registry: ""
    repository: glasswallsolutions/policy-management-api
    tag: develop-4cd7ac0
  transactioneventapi:
    registry: ""
    repository: glasswallsolutions/transactioneventapi
    tag: develop-68b5973
  transactionqueryaggregator:
    tag: develop-49884c7
