apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: management-ui
  name: {{ .Values.service.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.port }}