environment:
deployment:
  name: icap-management-portal
  port: 8080
service:
  name: icap-management-portal-service
  port: 80
imagestore:
  icapmanagementui:
    repository: glasswallsolutions/icap-management-ui
    tag: main-72b0d7b
