environment:
deployment:
  name: icap-management-ui
  port: 8080
service:
  name: icap-management-ui-service
  port: 80
imagestore:
  icapmanagementui:
    repository: glasswallsolutions/icap-management-ui
    tag: main-latest