apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadataName }}
  labels:
    app: {{ .Values.appLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{.Values.appLabel}}
    spec:
      containers:
        - image: "{{ .Values.imagestore.busybox.registry }}{{ .Values.imagestore.busybox.repository }}:{{ .Values.imagestore.busybox.tag }}"
          name: {{.Values.metadataName}}
          command:
            - sleep
            - infinity
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      imagePullSecrets:
        - name: overprovisioning-registry-credential
      priorityClassName: {{ .Values.priorityClassName }}
