environment:
nginx:
  name: file-drop-nginx
  deployment:
    name: file-drop-nginx
    containerPort: 80
  service:
    type: ClusterIP
    name: nginx-service
    port: 80
  probes:
    enabled: false
  replicaCount: 1
  configuration:
    NGINX_ENTRYPOINT_QUIET_LOGS: "1"
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  probes:
    enabled: false
  ingress:
    name: file-drop-service-ingress
    port: 80
    host: file-drop-develop.uksouth.cloudapp.azure.com
    path: /(.*)
filedropui:
  name: file-drop-ui
  deployment:
    name: file-drop-ui
    port: 80
  service:
    name: file-drop-ui-service
    port: 80
  ingress:
    enabled: false
    annotations: {}
    path: /
    tls: []
filedropapi:
  name: file-drop-api
  deployment:
    name: file-drop-api
    port: 80
  service:
    name: file-drop-api-service
    port: 80
  ingress:
    enabled: false
    annotations: {}
    path: /api
    tls: []
  limits:
    cpu: 1
    memory: 10000Mi
  requests:
    memory: 250Mi
    cpu: 0.2
imagestore:
  icapfiledropui:
    registry: ""
    repository: glasswallsolutions/icap-filedrop-ui
    tag: develop-fd1a289
  icapfiledropapi:
    registry: ""
    repository: glasswallsolutions/icap-filedrop-api
    tag: develop-4a4bf4b
  nginx:
    registry: ""
    repository: nginx
    tag: alpine
