apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "transactioneventapi.fullname" . }}-event-api
  labels:
    app: {{ template "transactioneventapi.name" . }}
    chart: {{ template "transactioneventapi.chart" . }}
    draft: {{ .Values.draft | default "draft-app" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.transactioneventapi.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "transactioneventapi.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "transactioneventapi.name" . }}
        draft: {{ .Values.draft | default "draft-app" }}
        release: {{ .Release.Name }}
      annotations:
        buildID: {{ .Values.buildID | default "" | quote }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.imagestore.transactioneventapi.registry }}{{ .Values.imagestore.transactioneventapi.repository }}:{{ .Values.imagestore.transactioneventapi.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.transactioneventapi.deployment.containerPort }}
              protocol: TCP
          {{- if .Values.transactioneventapi.probes.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- end }}
          env:
            - name: TransactionStoreConnectionStringCsv
              valueFrom:
                secretKeyRef:
                  name: transactionstoresecret
                  key: TransactionStoreConnectionStringCsv
            - name: ASPNETCORE_URLS
              value: "https://+:443"
            {{- $root := . }}
            {{- range $ref, $values := .Values.transactioneventapi.secrets }}
            {{- range $key, $value := $values }}
            - name: {{ $ref }}_{{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "transactioneventapi.fullname" $root }}-{{ $ref | lower }}
                  key: {{ $key }}
            {{- end }}
            {{- end }}
          resources:
{{ toYaml .Values.transactioneventapi.resources | indent 12 }}
    {{- with .Values.transactioneventapi.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.transactioneventapi.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.transactioneventapi.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      imagePullSecrets:
        - name: transactioneventapi-registry-credential