apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.nginx.ingress.name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    service.beta.kubernetes.io/azure-dns-label-name: {{ .Values.nginx.ingress.host }}
    cert-manager.io/issuer: selfsigning-issuer-nginx
spec:
  tls:
  - hosts:
    - {{ .Values.nginx.ingress.host }}
    secretName: tls-certficate-secret
  rules:
  - host: {{ .Values.nginx.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.nginx.service.name }}
          servicePort: {{ .Values.nginx.service.port }}
        path: {{ .Values.nginx.ingress.path }}

      
